FROM docker.io/golang:1.16.5-buster

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# INSTALL UPX SHELLCHECK PIP + CLEANUP
RUN apt-get update && apt-get -y -q --no-install-recommends install upx-ucl=3.95-1 python-pip=18.1-5 shellcheck=0.5.0-3 unzip=6.0-23+deb10u2 lftp=4.8.4-2 git-lfs=2.7.1-1+deb10u1 && apt-get -y -q autoremove && apt-get -y -q clean && rm -rf /var/lib/apt/lists/*

# INSTALL GOLANGCI LINT
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1

# INSTALL GORELEASER
RUN wget -nv https://github.com/goreleaser/goreleaser/releases/download/v0.172.0/goreleaser_amd64.deb && dpkg -i goreleaser_amd64.deb

# INSTALL MINIO CLI
RUN wget -nv https://dl.min.io/client/mc/release/linux-amd64/mc && mv mc /usr/bin/ && chmod +x /usr/bin/mc
