FROM docker.io/golang:1.17.6-bullseye

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# INSTALL UPX SHELLCHECK PIP + CLEANUP
RUN apt-get update && apt-get -y -q --no-install-recommends install upx-ucl python3-pip shellcheck unzip lftp git-lfs && apt-get -y -q autoremove && apt-get -y -q clean && rm -rf /var/lib/apt/lists/*

# INSTALL GOLANGCI LINT
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0

# INSTALL GORELEASER
RUN wget -O goreleaser_amd64.deb -nv https://github.com/goreleaser/goreleaser/releases/download/v1.3.1/goreleaser_v1.3.1_amd64.deb && dpkg -i goreleaser_amd64.deb

# INSTALL MINIO CLI
RUN wget -nv https://dl.min.io/client/mc/release/linux-amd64/mc && mv mc /usr/bin/ && chmod +x /usr/bin/mc
