FROM docker.io/python:3.9.9-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && \
apt-get -y -q --no-install-recommends install curl=7.74.0-1.3+b1 lftp=4.8.4-2+b1 git=1:2.30.2-1 git-lfs=2.13.2-1+b5 make=4.3-4.1 && \
apt-get -y -q autoremove && \
apt-get -y -q clean && \
rm -rf /var/lib/apt/lists/* && \
pip install --no-cache-dir poetry==1.1.12
